---
name: build-and-test
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  test:
    strategy:
      matrix:
        go: ["1.18", "1.19"]
        os: [macos-latest, ubuntu-latest]
    name: "build and test"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: build
        run: go build .
      - name: test
        run: go run github.com/onsi/ginkgo/v2/ginkgo run ./...
